name: Build

on: [push]

jobs:
  test:
    runs-on: macos-12
    name: A job to run test in FreeBSD
    steps:
    - name: Checkout FreeBSD-ports
      uses: actions/checkout@v3
      with:
        repository: pfsense/FreeBSD-ports
        path: FreeBSD-ports
   
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        path: FreeBSD-ports/net/pfSense-pkg-zerotier
    
    - name: Tarball everything since FreeBSD task rsyncs stuff back n forth (speed this up)
      run: |
        tar -zcvf FreeBSD-ports.tar.gz FreeBSD-ports/
        rm -rf FreeBSD-ports
    
    # Building in FreeBSD this way takes a looong time
    - name: Build in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0
      with:
        release: 12.3
        usesh: true

        run: |
          echo "ALLOW_UNSUPPORTED_SYSTEM=YES" >> /etc/make.conf
          OLD_DIR=$(pwd)
          ls -lah
          tar -xf FreeBSD-ports.tar.gz
          rm FreeBSD-ports.tar.gz
          cd FreeBSD-ports/net/pfSense-pkg-zerotier
          make clean ; make package
          ls -lah work/pkg/
          cp work/pkg/pfSense-pkg-zerotier-*.txz $OLD_DIR/
          cd $OLD_DIR
          ls -lah
          rm -rf FreeBSD-ports
      
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
      id: auto_tagger

    - name: Tag release w/ artifact
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: ${{ steps.auto_tagger.outputs.new_tag }}
        files: |
          pfSense-pkg-zerotier-*.txz
          
