name: Build

on: [push]

jobs:
  test:
    runs-on: macos-12
    name: A job to run test in FreeBSD
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        path: pfSense-pkg-zerotier
    
    - name: Get ZIP of FreeBSD repo
      run: |
        wget https://github.com/pfsense/FreeBSD-ports/archive/refs/heads/devel.zip
        mv devel.zip FreeBSD-ports-devel.zip
        ls -lah
    
    # Building in FreeBSD this way takes a looong time
    - name: Build in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0
      with:
        release: 12.3
        usesh: true

        run: |
          echo "ALLOW_UNSUPPORTED_SYSTEM=YES" >> /etc/make.conf
          OLD_DIR=$(pwd)
          ls -lah
          unzip -q FreeBSD-ports-devel.zip
          rm FreeBSD-ports-devel.zip
          ls -lah
          mv pfSense-pkg-zerotier FreeBSD-ports/net/
          cd FreeBSD-ports-devel/net/pfSense-pkg-zerotier
          make clean ; make package
          ls -lah work/pkg/
          cp work/pkg/pfSense-pkg-zerotier-*.txz $OLD_DIR/
          cd $OLD_DIR
          ls -lah
          rm -rf FreeBSD-ports
      
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
      id: auto_tagger

    - name: Tag release w/ artifact
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: ${{ steps.auto_tagger.outputs.new_tag }}
        files: |
          pfSense-pkg-zerotier-*.txz
          
